First_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='First_Project/index.html'), name='index'),
    path('authorization/', include('authorization.urls')),
    path('authorization/', include('django.contrib.auth.urls')),
]

authorization/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import LoginView, LogoutView

from authorization import views

app_name = 'authorization'

urlpatterns = [
    path('signup/', views.UserCreateView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='authorization/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

authorization/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager

# Create your models here.
class UserCreateManager(BaseUserManager):
    def _create_user(self, username, email, first_name, is_staff, is_superuser, password, **kwargs):
        if not username:
            raise ValueError('Username is mandatory')
        if not email:
            raise ValueError('Email is mandatory')
        email = self.normalize_email(email)
        if not first_name:
            raise ValueError('First Name is mandatory')
        user = self.model(username=username, email=email, first_name=first_name, is_staff=is_staff,
                            is_superuser=is_superuser, **kwargs)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email, first_name, password=None, **kwargs):
        return self._create_user(username, email, first_name, False, False, password, **kwargs)

    def create_superuser(self, username, email, first_name, password=None, **kwargs):
        return self._create_user(username, email, first_name, True, True, password, **kwargs)


class UserCreate(AbstractUser):
    object = UserCreateManager()
    username = models.CharField(unique=True, max_length=10)
    email = models.EmailField(unique=True)
    birth_date = models.DateField(blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name',]

authorization/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from authorization import models


class UserCreateForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = models.UserCreate
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'birth_date')


class UserUpdateForm(UserChangeForm):
    class Meta(UserChangeForm):
        model = models.UserCreate
        fields = ('username', 'first_name', 'last_name', 'birth_date')

authorization/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from authorization import forms
from authorization import models
# Create your views here.

class UserCreateView(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'authorization/signup.html'

authorization/templates/authorization/login.html
{% extends "First_Project/base.html" %}

{% block body_content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
  </form>
{% endblock body_content %}

authorization/templates/authorization/signup.html
{% extends "First_Project/base.html" %}

{% block body_content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Sign Up">
  </form>
{% endblock body_content %}

templates/First_Project/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Test Project</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Sample</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="admin">Admin</a>
          </li>
        </ul>
        {# Items to the right #}
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="#">
                  Welcome {{ user.first_name }}!
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'authorization:logout' %}">
                  Logout
                </a>
            </li>
          {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'authorization:login' %}">
                  Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'authorization:signup' %}">
                  Signup
                </a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    {% block body_content %}
      <div class="container">

      </div>
    {% endblock body_content %}
  </body>
</html>

templates/First_Project/index.html
{% extends "First_Project/base.html" %}

{% block body_content %}
  <div class="jumbotron">
    <h1>Welcome to Test Project</h1>
  </div>
{% endblock body_content %}